server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service          #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
            - After=2024-10-11T17:55:33.795001100+08:00[Asia/Shanghai]
#            - My=diamond


        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service          #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由

        - id: pay_routh3 #pay_routh3
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
              - Path=/pay/gateway/filter/**              # 断言，路径相匹配的进行路由
          filters:
              - AddRequestHeader=X-Request-atguigu1,atguiguValue1  # 请求头kv，若一头含有多参则重写一行设置
              - My=atguigu
#              - AddRequestHeader=X-Request-atguigu2,atguiguValue2
#              - RemoveRequestHeader=sec-fetch-site      # 删除请求头sec-fetch-site
#              - SetRequestHeader=sec-fetch-mode, Blue-yanang # 将请求头sec-fetch-mode对应的值修改为Blue-yanang
#
#              - AddRequestParameter=customerId,9527001 # 新增请求参数Parameter：k ，v
#              - RemoveRequestParameter=customerName   # 删除url请求参数customerName，你传递过来也是null
#
#              - AddResponseHeader=X-Response-atguigu, BlueResponse # 新增回应参数X-Response-atguigu并设值为BlueResponse
#              - SetResponseHeader=Date,2099-11-11 # 设置回应头Date值为2099-11-11
#              - RemoveResponseHeader=Content-Type # 将默认自带Content-Type回应属性删除

#              - PrefixPath=/pay  # http://localhost:9527/pay/gateway/filter
#              - SetPath=/pay/gateway/{segment}  # {segment}表示占位符，你写abc也行但要上下一致
#              - RedirectTo=302, http://www.atguigu.com/ # 访问path跳转到http://www.atguigu.com/